### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-aws#557]
Spring Cloud AWS has been a community project since its initial commit 11e8821afb85205398288ed728bbdee4872ec0ab on 2011-02-10 and when it joined spring cloud on [2014-10-25](https://github.com/spring-cloud/spring-cloud-aws/commits/1.0.x?after=5f933c9e679149efa319b07de32b68a7b646e8a8+279).

The project has lacked a community lead since early 2019.

As noted in the [2020.0.0-M1 blog post](https://spring.io/blog/2020/04/17/spring-cloud-2020-0-0-m1-released), spring cloud aws is no longer part of the release train. This follows the guidelines set forth in the [Simplifying the Spring Cloud Release Train](https://spring.io/blog/2019/07/24/simplifying-the-spring-cloud-release-train).

## Looking for Maintainers

The Spring Cloud team is currently looking for maintainers to take over the Spring Cloud AWS project.

Roles and responsibilities:

- Review Pull Requests (PRs)
- Triage issues
- Fix bugs
- Implement new features

## Current State

The 2.2.x branch is the last branch that will be in the Hoxton release train. Breaking changes can not happen in this branch.

## Future State

Breaking changes can happen on the master branch. This is where the stand alone project will be released from. A number of things need to happen:

- [ ] Fork the project to a new github organization
- [ ] Change package names
- [ ] Change maven group id

Updating to the 2.x version of the aws java sdk is already in progress #524.

## Feedback

Please provide any feedback as comments below. This issue will be updated as new information is made available.

**Comment by spencergibb** [comment]
@maciejwalkowiak has volunteered to help as a maintainer.

**Comment by josecarlosweb** [comment]
Hi, I'm interested.

**Comment by ErnestOrt** [comment]
Hi, interested as well.

**Comment by giova333** [comment]
Hi, I am interested

**Comment by jmirc** [comment]
Hi, I am interested

**Comment by eddumelendez** [comment]
I would like to join and help for the future of the project 🙂

**Comment by terancet** [comment]
Hi, 

I am interested as well

**Comment by rbailen** [comment]
Hi friends,

I would like to participate in the challenge with you !

**Comment by msilvadev** [comment]
Hi, I am interested too

**Comment by asalan316** [comment]
Being a spring cloud developer, I am eager to help.

**Comment by slachiewicz** [comment]
Hi, I'm also interested

**Comment by asanera** [comment]
Hi, I'm interested.

**Comment by draganilievski** [comment]
Hi, i am interested.

**Comment by OnomeOkuma** [comment]
Hi, I am interested

**Comment by FelipeAdorno** [comment]
I'm interested too :)

**Comment by RobbieJVMW** [comment]
I’m interested

**Comment by darshan-elsevier** [comment]
I am interested in maintaining and/or volunteering in the project. Lemme know how/when

**Comment by metamorphiccode** [comment]
hello , i am interest in

**Comment by ask4gilles** [comment]
Hi there @maciejwalkowiak @spencergibb ,
Could be fun, I’m in too!

**Comment by witusx93** [comment]
I’d like to try in open source

**Comment by adilfulara** [comment]
I would like to help too

**Comment by fegm22** [comment]
Hi! I would love to help :)

**Comment by dayanfcosta** [comment]
I'd love to help maintaining this project. :-)

**Comment by sferrazjr** [comment]
I'm interested too :)

**Comment by skapil** [comment]
Hi, I would love to help!!

**Comment by jabrena** [comment]
I would like to help :)

**Comment by sombhattacharyya1983** [comment]
I would love to help in any capacity. Is there any getting started with documentation/etiquette ? Please let know what should I do to go forward.

**Comment by alokkulkarni** [comment]
hi I am interested in joining

**Comment by alokkulkarni** [comment]
please do let me know how to go forward?

**Comment by r-kgy** [comment]
Hi, I would love to help also!!

**Comment by trilokkatni** [comment]
> Spring Cloud AWS has been a community project since its initial commit [11e8821](https://github.com/spring-cloud/spring-cloud-aws/commit/11e8821afb85205398288ed728bbdee4872ec0ab) on 2011-02-10 and when it joined spring cloud on [2014-10-25](https://github.com/spring-cloud/spring-cloud-aws/commits/1.0.x?after=5f933c9e679149efa319b07de32b68a7b646e8a8+279).
> 
> The project has lacked a community lead since early 2019.
> 
> As noted in the [2020.0.0-M1 blog post](https://spring.io/blog/2020/04/17/spring-cloud-2020-0-0-m1-released), spring cloud aws is no longer part of the release train. This follows the guidelines set forth in the [Simplifying the Spring Cloud Release Train](https://spring.io/blog/2019/07/24/simplifying-the-spring-cloud-release-train).
> 
> ## Looking for Maintainers
> The Spring Cloud team is currently looking for maintainers to take over the Spring Cloud AWS project.
> 
> Roles and responsibilities:
> 
> * Review Pull Requests (PRs)
> * Triage issues
> * Fix bugs
> * Implement new features
> 
> ## Current State
> The 2.2.x branch is the last branch that will be in the Hoxton release train. Breaking changes can not happen in this branch.
> 
> ## Future State
> Breaking changes can happen on the master branch. This is where the stand alone project will be released from. A number of things need to happen:
> 
> * [ ]  Fork the project to a new github organization
> * [ ]  Change package names
> * [ ]  Change maven group id
> 
> Updating to the 2.x version of the aws java sdk is already in progress #524.
> 
> ## Feedback
> Please provide any feedback as comments below. This issue will be updated as new information is made available.

I'm interested

**Comment by karmanov** [comment]
Hi, I would more than happy to help with this project.

**Comment by BartoszCoyote** [comment]
I would like to help :)

**Comment by alibenmessaoud** [comment]
Hi, I would love to help also!

**Comment by siviwes** [comment]
Interested to help and learn

**Comment by kappaj2** [comment]
Willing to learn and eager to help where / when I can.
Doing Spring development outside of AWS, AWS Lambda's and SpringBoot apps on AWS.

**Comment by metamorphiccode** [comment]
Hello , i am in too

**Comment by HansOspina** [comment]
I am interested

**Comment by jcvillalta03** [comment]
I am interested!

**Comment by tmnuwan12** [comment]
I am interested.

**Comment by tmnuwan12** [comment]
Not sure this is the correct place but I would like some CI Pipeline for integration tests. So that we can run before the PR merge.

**Comment by maciejwalkowiak** [comment]
Integration tests fail to run at this stage even when I execute them locally. If we run it for PRs we would need to get some credits from AWS as it can get expensive. 

At this stage I'd like to get regular tests running for PRs.

**Comment by maciejwalkowiak** [comment]
It's great to see so many people interested! I started going through issues and PRs closing ones that are not relevant anymore and merging low handing fruits. Roadmap for 3.0 and potentially 2.3 is still shaping. At this stage I would like us to fix all bugs and add non-breaking enhancements to 2.2.x. Take a look please at issues with "Help Wanted" label and see in comments if someone has not yet started working on it.

https://github.com/spring-cloud/spring-cloud-aws/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

Starting from today I am also on Spring Cloud AWS gitter: https://gitter.im/spring-cloud/spring-cloud-aws so if you would like to chat in more real time manner you are welcome to join :-)

**Comment by bsamartins** [comment]
🙋‍♂️

**Comment by spencergibb** [comment]
Thanks, everyone for volunteering! I'm super impressed by the show of support. For the immediate near term, we have added @eddumelendez alongside @maciejwalkowiak as a maintainer. Our measure going forward will be showing sustained involvement in fixing bugs, enhancements, PR reviews, etc... Maciej has already created a list of "help wanted" issues. That would be a good starting point.

**Comment by arunkpatra** [comment]
I would like to help. Will catch up with @maciejwalkowiak
